routes/web.php
<?php

/* 
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/   

/*Route::get('/', function () {
    return view('frontend.home');
});*/ 


 
  

 
Auth::routes();

Route::get('contact-us', function(){

	return view('frontend.contact.contact');
});



Route::get('/home',function(){
	return redirect('dashboard');
});

Route::resource('join-us','JointUcController');
Route::get('search', 'HomeController@search');

Route::get('/','HomeController@index');

Route::get('product-details/{id}','ShoppingviewController@productDetails');
Route::get('product-view/{link}','ShoppingviewController@viewProduct');



Route::post('add-to-cart','ShoppingController@addToCart');

Route::get('cart','ShoppingController@cartDetails');
Route::get('Special-product','SpecialsShowController@specialProduct');

 
Route::get('category-product/{link}','ProductListController@productList');
Route::get('sub-category-product/{id}','ProductListController@subproductList');
Route::get('sub-sub-category-product/{id}','ProductListController@ssproductList');

Route::get('page/{link}', 'PagesController@show');


 


Route::middleware(['admin'])->group(function () {

Route::get('checkout','CheackoutController@checkoutView');
//Route::get('cart-show','CheackoutController@cartDetail');
Route::get('load-payment-methode/{id}','CheackoutController@loadInstruction');
Route::post('order-form','OrderViewController@orderForm');
Route::get('order/{id}','OrderViewController@order');
Route::get('/user-profile','ProfileController@userprofile');
Route::post('/userProfileUpdate','ProfileController@changeUserProfile');
Route::get('/myOrderList','ProfileController@orderList');
Route::get('wishlist','WishlistController@index');
Route::get('wishlist-store','WishlistController@store');
Route::get('wishlist-delete/{id}','WishlistController@delete');

 
	Route::group(['middleware'=>['auth']],function(){



		Route::resource('/users', 'UsersController');
		Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

		Route::resource('pages','PageController');
		Route::resource('menu','MenuController');
		Route::resource('sub-menu','SubmenuController');
		Route::resource('sub-sub-menu','SubsubmenuController');
		Route::resource('others-info','OthersController');
		Route::resource('Slider-info','SliderController');
		Route::resource('Social-links','SociallinkController');
		Route::resource('payment-methode','PaymentController');

		Route::resource('admin-discount','DiscountController');


		Route::get('other/about','OthersController@about');
		
		Route::get('page-menu','MenuController@page');

		Route::resource('category','CategoryController');
		Route::resource('sub-category','SubcategoryController');
		Route::resource('subsub-category','SubSubCategoryController');
		Route::resource('attribute','AttributeController');

		Route::resource('sub-attribute','SubAttributeController');
		Route::resource('all-brand','BrandController');
		Route::resource('add-manager','AdsController');

		Route::resource('product-create','ProductController');
		Route::get('load-sub-cat/{id}','ProductController@loadSubCat');
		Route::get('load-subsub-cat/{id}','ProductController@loadSubSubCat');
		Route::resource('orders','AllOrderController');

		Route::get('delivered','AllOrderController@delivered');
        Route::get('cancel-order','AllOrderController@cancelOrder');

        Route::get('received','AllOrderController@received');

		

    });

	Route::get('/cart-remove-item/{rowId}', 'ShoppingController@remove');
	Route::get('/increment/{rowId}', 'ShoppingController@increment');
	Route::get('/decrement/{rowId}', 'ShoppingController@decrement');
	Route::get('/clear-cart', 'ShoppingController@cartClear');


 






});

resources/views/backend/page/create.blade.php
@extends('backend.app')
@section('content')
<div class="tab_content">

<h3 class="box_title">Add New 
 <a href="{{route('pages.index')}}" class="btn btn-default pull-right"> <i class="ion ion-navicon-round"></i> View All </a></h3>
	{!! Form::open(array('route' => 'pages.store','class'=>'form-horizontal','files'=>true)) !!}
        <div class="form-group  {{ $errors->has('link') ? 'has-error' : '' }}">
            
            {{Form::label('link', 'Page link', array('class' => 'col-md-3 control-label'))}}
            <div class="col-md-8">
                <div class="input-group">
                    <div class="input-group-addon">{{URL::to('page')}}/</div>
                    {{Form::text('link','',array('class'=>'form-control','placeholder'=>'Page link','required'))}}
                </div>
                @if ($errors->has('link'))
                    <span class="help-block">
                        <strong>{{ $errors->first('link') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <div class="form-group">
            {{Form::label('name', 'Page Name', array('class' => 'col-md-3 control-label'))}}
            <div class="col-md-8">
                {{Form::text('name','',array('class'=>'form-control','placeholder'=>'Page Name','required'))}}
            </div>
        </div>
        <div class="form-group">
            {{Form::label('title', 'Page Title', array('class' => 'col-md-3 control-label'))}}
            <div class="col-md-8">
                {{Form::textArea('title','',array('class'=>'form-control tinymce','placeholder'=>'Page Title','required','rows'=>'2'))}}
            </div>
        </div>
        <div class="form-group {{ $errors->has('file') ? 'has-error' : '' }}">
            {{Form::label('file', 'Pdf file', array('class' => 'col-md-3 control-label'))}}
            <div class="col-md-8">
                {{Form::file('file',array('class'=>'form-control'))}}
                 @if ($errors->has('file'))
                        <span class="help-block" style="display:block">
                            <strong>{{ $errors->first('file') }}</strong>
                        </span>
                    @endif
                    <br>
                    <b>OR</b>
            </div>
        </div>
        <div class="form-group">
            {{Form::label('description', 'Description', array('class' => 'col-md-3 control-label'))}}
            <div class="col-md-8">
                {{Form::textArea('description','',array('class'=>'form-control tinymce','placeholder'=>'Write some thing about page','rows'=>'5'))}}
            </div>
        </div>
        <div class="form-group">
            {{Form::label('status', 'Status', array('class' => 'col-md-3 control-label'))}}
            <div class="col-md-8">
                {{Form::select('status', array('1' => 'Active', '2' => 'Inactive'),'1', ['class' => 'form-control'])}}
            </div>
        </div>
        
        
        <div class="from-group col-md-6 multiple_upload">
        <!-- Load multiple photo -->
        </div>

	    <div class="form-group">
	        <div class="col-md-9 col-md-offset-3">
	            <button type="submit" class="btn btn-primary">Submit</button>
	        </div>
	    </div>
      </div>
	{!! Form::close() !!}

@endsection

resources/views/backend/page/edit.blade.php
@extends('backend.app')
@section('content')


<h3 class="box_title">Edit 
 <a href="{{route('pages.index')}}" class="btn btn-default pull-right"> <i class="ion ion-navicon-round"></i> View All </a>
 </h3>
    {!! Form::open(array('route' => ['pages.update', $data->id],'method'=>'PUT','class'=>'form-horizontal','files'=>true)) !!}
        <div class="form-group ">
            
            {{Form::label('link', 'Page link', array('class' => 'col-md-3 control-label'))}}
            <div class="col-md-8">
                <div class="input-group">
                    <div class="input-group-addon">{{URL::to('page')}}/</div>
                    {{Form::text('link',$data->link,array('class'=>'form-control','placeholder'=>'Page link','required'))}}
                </div>
            </div>
        </div>
        <div class="form-group">
            {{Form::label('name', 'Page Name', array('class' => 'col-md-3 control-label'))}}
            <div class="col-md-8">
                {{Form::text('name',$data->name,array('class'=>'form-control','placeholder'=>'Page Name','required'))}}
            </div>
        </div>
        <div class="form-group">
            {{Form::label('title', 'Page title', array('class' => 'col-md-3 control-label'))}}
            <div class="col-md-8">
                {{Form::text('title',$data->title,array('class'=>'form-control','placeholder'=>'Page title','required'))}}
            </div>
        </div>
        <div class="form-group {{$errors->has('file') ? ' has-error' : '' }}">
            {{Form::label('file', 'Pdf File', array('class' => 'col-md-3 control-label'))}}
            <div class="col-md-8">
            @if($data->file!=null)
                <div id="pdf">
                  <object type="application/pdf" data='{{asset("public/files/page/$data->file")}}?#zoom=80&scrollbar=0&toolbar=0&navpanes=0' id="pdf_content">
                    <p>Not Found PDF File.</p>
                  </object>
                </div>
            @endif
                {{Form::file('file',array('class'=>'form-control'))}}
                 @if ($errors->has('file'))
                    <span class="help-block">
                        <strong>{{ $errors->first('file') }}</strong>
                    </span>
                @endif
            </div>
        </div>
        <div class="form-group">
            {{Form::label('description', 'Description', array('class' => 'col-md-3 control-label'))}}
            <div class="col-md-8">
                {{Form::textArea('description',$data->description,array('class'=>'form-control tinymce','placeholder'=>'Write some thing about page','rows'=>'5'))}}
            </div>
        </div>
        
        <div class="form-group">
            {{Form::label('status', 'Status', array('class' => 'col-md-3 control-label'))}}

            <div class="col-md-8">
                {{Form::select('status', array('1' => 'Active', '2' => 'Inactive'),$data->status, ['class' => 'form-control'])}}
            </div>
        </div>
       
           
            {{Form::hidden('id',$data->id)}}
        <div class="form-group">
            <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
      
	{!! Form::close() !!}

@endsection

resources/views/backend/page/index.blade.php
@extends('backend.app')
@section('content')

<div class="tab_content">

  <h3 class="box_title">Pages
 <a href="{{route('pages.create')}}" class="btn btn-default pull-right"> <i class="ion ion-plus"></i> Add new </a></h3>
        <table class="table table-striped table-hover table-bordered center_table" id="my_table">
            <thead>
                <tr>
                    <th>SL</th>
                    <th>Page Name</th>
                     <th>Page Link </th>
                    <th>Status</th>
                    <th>Created At</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            <? $i=1; ?>
            @foreach($allData as $data)
                <tr>
                    <td>{{$i++}}</td>
                    <td><a href="{{route('pages.show',$data->id)}}">{{$data->name}}</a></td>
                    <td><a href="{{URL::to('page/'.$data->link)}}" target="_blank">{{URL::to('page/'.$data->link)}}</a></td>

                    <td><i class="{{($data->status==1)? 'fa fa-check-circle text-success' : 'fa fa-times-circle'}}"></i></td>
                    <td>{{$data->created_at}}</td>
                    <td>
        {!! Form::open(array('route' => ['pages.destroy',$data->id],'method'=>'DELETE')) !!}
            <button type="submit" class="btn btn-xs btn-danger" onclick="return deleteConfirm()"><i class="fa fa-trash"></i></button>
        {!! Form::close() !!}
                    </td>

                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="pull-right">
        {{$allData->render()}} 
        </div>
  </div>


@endsection

resources/views/backend/page/packgedetails.blade.php
@extends('backend.app')
@section('content')
<h3 class="box_title">Page Details
  <a href="{{route('pages.index')}}" class="btn btn-default pull-right viewAll"> <i class="ion ion-navicon-round"></i>&nbsp; View All</a> 
  <a href="{{route('pages.edit',$data->id)}}" class="btn btn-default pull-right"> <i class="fa fa-pencil-square-o"></i> Edit</a> 
 </h3>
    <section class="col-md-12">
        <div class="hotel-view-main padding-top padding-bottom">
            <div class="p">
                <div class="journey-block">
           
                    <div class="col-md-12">
                        <div class="service_head">
                            <h2>{{$data->name}}</h2>
                            <div class="service_info">
                                <h5><b>Title: </b> {{$data->title}}</h5>
                            </div>
                            @if($data->file!=null)
                                <div id="pdf">
                                  <object type="application/pdf" data='{{asset("public/files/page/$data->file")}}?#zoom=110&scrollbar=0&toolbar=0&navpanes=0' id="pdf_content">
                                    <p>Not Found PDF File.</p>
      
                                  </object>
                                </div>
                            @endif
                            <div><b><u>Description:</u></b><br><? echo $data->description ?></div>
                        </div>
                    </div><!-- End col-md-11 -->

                    
    </section>
<!-- STYLE CSS-->

@endsection